CREATE DATABASE HOTELMANAGMENT
USE HOTELMANAGMENT

CREATE TABLE USER(
	ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    MOBILE_NUMBER VARCHAR(20),
    EMAIL VARCHAR(40),
    PASSWORD VARCHAR(25),
    PRIMARY KEY(ID),
    UNIQUE KEY(EMAIL)
);
drop table user
SELECT * FROM USER

CREATE TABLE ROOMS(
  ID INT  NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20),
  LAST_NAME VARCHAR(20), 
  MOBILE_NUMBER VARCHAR(20),
  EMAIL VARCHAR(40),
  ROOM_NUMBER INT NOT NULL, 
  ROOM_TYPE VARCHAR(20) NOT NULL,
  NUMBERS_OF_GUESTS INT NOT NULL,
  CHECK_IN_DATE DATE NOT NULL,
  CHECK_OUT_DATE DATE NOT NULL,
  ESTIMATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ROOM_CHECKED_IN tinyint(1), 
  UNIQUE KEY(ROOM_NUMBER),
  PRIMARY KEY (ID)
);
DROP TABLE ROOMS
SELECT * FROM ROOMS

CREATE TABLE ADMIN(
  ID INT  NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(40) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY(EMAIL)
)
DROP TABLE ADMIN
insert into ADMIN values(
	1,
	'Admin',
	'Admin',
	'admin@gmail.com',
    'admin@123'
)
SELECT * FROM ADMIN

CREATE TABLE VISITOR(
ID INT  NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20), 
NUMBERS_OF_GUESTS INT NOT NULL,
CHECK_IN_DATE DATE NOT NULL,
CHECK_OUT_DATE DATE NOT NULL,
ROOM_CHECK_STATUS tinyint(1),
PRIMARY KEY (ID)
) 
DROP TABLE VISITOR
SELECT * FROM VISITOR

